############## DOCKER INSTALL PLAYBOOK ################
########## COMMAND # ansible-playbook-2.7 -i -s docker_create.yml ############


---
- hosts: nodes
  tasks:
    - name: Installs docker
      become: yes
      yum: pkg=docker state=installed
      notify:
        - start docker
  handlers:
    - name: start docker
      become: yes
      service: name=docker state=started
